PRIORITY_FLOOD_FORWARD_ALWAYS = 1
PRIORITY_FLOOD_IF_PORT = PRIORITY_FLOOD_FORWARD_ALWAYS + 1
PRIORITY_SEND_FROM_MAC = PRIORITY_FLOOD_IF_PORT + 1
PRIORITY_ROUTE_CONNECTION = PRIORITY_SEND_FROM_MAC + 1
PRIORITY_BROADCAST_FROM_MAC = PRIORITY_ROUTE_CONNECTION + 1
PRIORITY_SEND_TO_MAC = PRIORITY_BROADCAST_FROM_MAC
